server:
  port: 8081


spring:
  application:
    name: service-client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        healthCheckPath: /health
        healthCheckInterval: 2s
        instance-id: service-client



order:
  service:
    url: http://order-service