server:
  port: 8999


spring:
  application:
    name: ratelimit-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        healthCheckPath: /health
        healthCheckInterval: 2s
        instance-id: ratelimit-gateway


zuul:
  routes:
    ratelimit-api:
      path: /ratelimit-api/**
      serviceId: service-client

  ratelimit:
    key-prefix: ratelimit-api
    enabled: true
    behind-proxy: true
    default-policy:
      limit: 10
      quota: 20
      refresh-interval: 60
      type: url

